In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Data Loading & Understanding

In [3]:
df = pd.read_csv("data/games-features.csv")
df

,QueryID,ResponseID,QueryName,ResponseName,ReleaseDate,RequiredAge,DemoCount,DeveloperCount,DLCCount,Metacritic,...,LegalNotice,Reviews,SupportedLanguages,Website,PCMinReqsText,PCRecReqsText,LinuxMinReqsText,LinuxRecReqsText,MacMinReqsText,MacRecReqsText
0,10,10,Counter-Strike,Counter-Strike,Nov 1 2000,0,0,1,0,88,...,,,English French German Italian Spanish Simplifi...,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
1,20,20,Team Fortress Classic,Team Fortress Classic,Apr 1 1999,0,0,1,0,0,...,,,English French German Italian Spanish,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
2,30,30,Day of Defeat,Day of Defeat,May 1 2003,0,0,1,0,79,...,,,English French German Italian Spanish,http://www.dayofdefeat.com/,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
3,40,40,Deathmatch Classic,Deathmatch Classic,Jun 1 2001,0,0,1,0,0,...,,,English French German Italian Spanish,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
4,50,50,Half-Life: Opposing Force,Half-Life: Opposing Force,Nov 1 1999,0,0,1,0,0,...,,,English French German Korean,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13352,567660,567660,Baseball Riot,Baseball Riot,Jan 17 2017,0,0,1,0,0,...,Copyright (c) 2016 10tons Ltd.,,English**languages with full audio support,http://www.10tons.com/Game/baseball_riot.html,Minimum:OS: Windows XP / Vista / 7 / 8 / 10Pro...,,,,,
13353,567860,567860,Passage 4,Passage 4,Dec 13 2016,0,0,1,0,0,...,2016 copyright by netmin e.K.,,English* French Italian German* Spanish Dutch*...,http://www.libredia.com,Minimum:OS: Windows 2000/XP/Vista/7/8/10Proces...,,,,,
13354,567940,567940,Piximalism,Piximalism,Sep 26 2019,0,0,1,0,0,...,,,English,NaN,Minimum:OS: Microsoft(r) Windows(r) XP / Vista...,Recommended:OS: Microsoft(r) Windows(r) XP / V...,,,,
13355,568150,568150,Technoball,Technoball,Dec 12 2016,0,0,1,0,0,...,,,English**languages with full audio support,NaN,Minimum:OS: Windows 7 (64-bit)Processor: 2.5 G...,,,,,
13356,559250,559250,Ghostlight Manor,Ghostlight Manor,Dec 12 2016,0,0,1,0,0,...,,The real draw here is the gameplay Digital Fut...,English**languages with full audio support,http://digitalfuturelab.com/ghostlight/,Minimum:OS: Windows 7 64 bitProcessor: Intel C...,,,,Minimum:OS: Mac OSX 10.10+ 64 bitProcessor: In...,

In [4]:
df.shape

(13357, 78)

In [5]:
df.head()

,QueryID,ResponseID,QueryName,ResponseName,ReleaseDate,RequiredAge,DemoCount,DeveloperCount,DLCCount,Metacritic,...,LegalNotice,Reviews,SupportedLanguages,Website,PCMinReqsText,PCRecReqsText,LinuxMinReqsText,LinuxRecReqsText,MacMinReqsText,MacRecReqsText
0,10,10,Counter-Strike,Counter-Strike,Nov 1 2000,0,0,1,0,88,...,,,English French German Italian Spanish Simplifi...,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
1,20,20,Team Fortress Classic,Team Fortress Classic,Apr 1 1999,0,0,1,0,0,...,,,English French German Italian Spanish,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
2,30,30,Day of Defeat,Day of Defeat,May 1 2003,0,0,1,0,79,...,,,English French German Italian Spanish,http://www.dayofdefeat.com/,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
3,40,40,Deathmatch Classic,Deathmatch Classic,Jun 1 2001,0,0,1,0,0,...,,,English French German Italian Spanish,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
4,50,50,Half-Life: Opposing Force,Half-Life: Opposing Force,Nov 1 1999,0,0,1,0,0,...,,,English French German Korean,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,

In [6]:
df.columns

Index(['QueryID', 'ResponseID', 'QueryName', 'ResponseName', 'ReleaseDate',
       'RequiredAge', 'DemoCount', 'DeveloperCount', 'DLCCount', 'Metacritic',
       'MovieCount', 'PackageCount', 'RecommendationCount', 'PublisherCount',
       'ScreenshotCount', 'SteamSpyOwners', 'SteamSpyOwnersVariance',
       'SteamSpyPlayersEstimate', 'SteamSpyPlayersVariance',
       'AchievementCount', 'AchievementHighlightedCount', 'ControllerSupport',
       'IsFree', 'FreeVerAvail', 'PurchaseAvail', 'SubscriptionAvail',
       'PlatformWindows', 'PlatformLinux', 'PlatformMac', 'PCReqsHaveMin',
       'PCReqsHaveRec', 'LinuxReqsHaveMin', 'LinuxReqsHaveRec',
       'MacReqsHaveMin', 'MacReqsHaveRec', 'CategorySinglePlayer',
       'CategoryMultiplayer', 'CategoryCoop', 'CategoryMMO',
       'CategoryInAppPurchase', 'CategoryIncludeSrcSDK',
       'CategoryIncludeLevelEditor', 'CategoryVRSupport', 'GenreIsNonGame',
       'GenreIsIndie', 'GenreIsAction', 'GenreIsAdventure', 'GenreIsCasual',
       'GenreIsStrategy', 'GenreIsRPG', 'GenreIsSimulation',
       'GenreIsEarlyAccess', 'GenreIsFreeToPlay', 'GenreIsSports',
       'GenreIsRacing', 'GenreIsMassivelyMultiplayer', 'PriceCurrency',
       'PriceInitial', 'PriceFinal', 'SupportEmail', 'SupportURL', 'AboutText',
       'Background', 'ShortDescrip', 'DetailedDescrip', 'DRMNotice',
       'ExtUserAcctNotice', 'HeaderImage', 'LegalNotice', 'Reviews',
       'SupportedLanguages', 'Website', 'PCMinReqsText', 'PCRecReqsText',
       'LinuxMinReqsText', 'LinuxRecReqsText', 'MacMinReqsText',
       'MacRecReqsText'],
      dtype='str')

In [7]:
df.dtypes.value_counts()

bool       35
str        23
int64      18
float64     2
Name: count, dtype: int64

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13357 entries, 0 to 13356
Data columns (total 78 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   QueryID                      13357 non-null  int64
 1   ResponseID                   13357 non-null  int64
 2   QueryName                    13356 non-null  str
 3   ResponseName                 13357 non-null  str
 4   ReleaseDate                  13357 non-null  str
 5   RequiredAge                  13357 non-null  int64
 6   DemoCount                    13357 non-null  int64
 7   DeveloperCount               13357 non-null  int64
 8   DLCCount                     13357 non-null  int64
 9   Metacritic                   13357 non-null  int64
 10  MovieCount                   13357 non-null  int64
 11  PackageCount                 13357 non-null  int64
 12  RecommendationCount          13357 non-null  int64
 13  PublisherCount               13357 non-null  int64
 14  ScreenshotCount              13357 non-null  int64
 15  SteamSpyOwners               13357 non-null  int64
 16  SteamSpyOwnersVariance       13357 non-null  int64
 17  SteamSpyPlayersEstimate      13357 non-null  int64
 18  SteamSpyPlayersVariance      13357 non-null  int64
 19  AchievementCount             13357 non-null  int64
 20  AchievementHighlightedCount  13357 non-null  int64
 21  ControllerSupport            13357 non-null  bool
 22  IsFree                       13357 non-null  bool
 23  FreeVerAvail                 13357 non-null  bool
 24  PurchaseAvail                13357 non-null  bool
 25  SubscriptionAvail            13357 non-null  bool
 26  PlatformWindows              13357 non-null  bool
 27  PlatformLinux                13357 non-null  bool
 28  PlatformMac                  13357 non-null  bool
 29  PCReqsHaveMin                13357 non-null  bool
 30  PCReqsHaveRec                13357 non-null  bool
 31  LinuxReqsHaveMin             13357 non-null  bool
 32  LinuxReqsHaveRec             13357 non-null  bool
 33  MacReqsHaveMin               13357 non-null  bool
 34  MacReqsHaveRec               13357 non-null  bool
 35  CategorySinglePlayer         13357 non-null  bool
 36  CategoryMultiplayer          13357 non-null  bool
 37  CategoryCoop                 13357 non-null  bool
 38  CategoryMMO                  13357 non-null  bool
 39  CategoryInAppPurchase        13357 non-null  bool
 40  CategoryIncludeSrcSDK        13357 non-null  bool
 41  CategoryIncludeLevelEditor   13357 non-null  bool
 42  CategoryVRSupport            13357 non-null  bool
 43  GenreIsNonGame               13357 non-null  bool
 44  GenreIsIndie                 13357 non-null  bool
 45  GenreIsAction                13357 non-null  bool
 46  GenreIsAdventure             13357 non-null  bool
 47  GenreIsCasual                13357 non-null  bool
 48  GenreIsStrategy              13357 non-null  bool
 49  GenreIsRPG                   13357 non-null  bool
 50  GenreIsSimulation            13357 non-null  bool
 51  GenreIsEarlyAccess           13357 non-null  bool
 52  GenreIsFreeToPlay            13357 non-null  bool
 53  GenreIsSports                13357 non-null  bool
 54  GenreIsRacing                13357 non-null  bool
 55  GenreIsMassivelyMultiplayer  13357 non-null  bool
 56  PriceCurrency                13357 non-null  str
 57  PriceInitial                 13357 non-null  float64
 58  PriceFinal                   13357 non-null  float64
 59  SupportEmail                 13355 non-null  str
 60  SupportURL                   13356 non-null  str
 61  AboutText                    13357 non-null  str
 62  Background                   13357 non-null  str
 63  ShortDescrip                 13357 non-null  str
 64  DetailedDescrip              13357 non-null  str
 65  DRMNotice                    13357 non-null  str
 66  ExtUserAcctNotice            13357 non-null  str
 67  HeaderImage                  13357 non-null  str
 68  LegalNotice                  13356 non-null  str
 69  Reviews                      13357 non-null  str
 70  SupportedLanguages           13357 non-null  str
 71  Website                      10196 non-null  str
 72  PCMinReqsText                13357 non-null  str
 73  PCRecReqsText                13357 non-null  str
 74  LinuxMinReqsText             13357 non-null  str
 75  LinuxRecReqsText             13357 non-null  str
 76  MacMinReqsText               13357 non-null  str
 77  MacRecReqsText               13357 non-null  str
dtypes: bool(35), float64(2), int64(18), str(23)
memory usage: 4.8 MB

# Exploring Data Set

#### Basic Statistics

In [9]:
df[["Metacritic", "PriceFinal", "RequiredAge", "SteamSpyPlayersEstimate"]].describe()

         Metacritic    PriceFinal   RequiredAge  SteamSpyPlayersEstimate
count  13357.000000  13357.000000  13357.000000             1.335700e+04
mean      12.285319      8.798596      0.837688             1.081638e+05
std       27.510876     13.606061      3.625701             1.006635e+06
min        0.000000      0.000000      0.000000             0.000000e+00
25%        0.000000      1.990000      0.000000             5.370000e+02
50%        0.000000      5.990000      0.000000             4.125000e+03
75%        0.000000      9.990000      0.000000             2.815800e+04
max       96.000000    449.990000     18.000000             9.068758e+07

#### Category Count

In [10]:
df["RequiredAge"].value_counts()

RequiredAge
0     12671
17      450
13       82
18       80
16       40
12       10
15        9
10        9
6         2
14        2
1         1
7         1
Name: count, dtype: int64

#### Genre: GenreIs* columns bata primary genre nikalne

In [11]:
genre_cols = [c for c in df.columns if c.startswith("GenreIs")]
def get_primary_genre(row):
    for col in genre_cols:
        if row[col]:
            return col.replace("GenreIs", "")
        return "Other"
    
df["Genre"] = df.apply(get_primary_genre, axis=1)
df["Genre"].value_counts()

Genre
Other      13038
NonGame      319
Name: count, dtype: int64

### Platform Breakdown

In [12]:
print("\nWindows:", df["PlatformWindows"].sum())
print("Linux:", df["PlatformLinux"].sum())
print("Mac:", df["PlatformMac"].sum())

Windows: 13355
Linux: 3057
Mac: 4562

#### Free vs Paid Games

In [13]:
print("\nFree Games:", df["IsFree"].sum())
print("\nPaid Games:", (~df["IsFree"]).sum())

Free Games: 1045

Paid Games: 12312

#### Correlation Numeric only

In [14]:
print("\n---Top correlation with Metacritic---")
num_cols = ["Metacritic", "PriceFinal", "SteamSpyPlayersEstimate", "RecommendationCount",
             "AchievementCount", "DLCCount"]
print(df[num_cols].corr(numeric_only=True)["Metacritic"].round(3))

---Top correlation with Metacritic---
Metacritic                 1.000
PriceFinal                 0.178
SteamSpyPlayersEstimate    0.163
RecommendationCount        0.120
AchievementCount           0.133
DLCCount                   0.034
Name: Metacritic, dtype: float64

# Data Cleaning

In [15]:
print("\nNull values before cleaning:") # counts null in ever columns
print(df.isnull().sum()[df.isnull().sum() > 0]) # filters to only show columns That have nulls

Null values before cleaning:
QueryName          1
SupportEmail       2
SupportURL         1
LegalNotice        1
Website         3161
dtype: int64

#### Review column Breakdown

In [20]:
print("=== REVIEWS COLUMN SUMMARY ===")
total = len(df)
has_review = (df['Reviews'].str.strip() != '').sum()
blank = (df['Reviews'].str.strip() == '').sum()

print(f"Total games       : {total}")
print(f"Has review text   : {has_review} ({has_review/total*100:.1f}%)")
print(f"Blank / empty     : {blank} ({blank/total*100:.1f}%)")

=== REVIEWS COLUMN SUMMARY ===
Total games       : 13357
Has review text   : 3314 (24.8%)
Blank / empty     : 10043 (75.2%)

#### Sample - Review vaya ko games

In [21]:
print("---Game Review Columns---")
with_reviews = df[df['Reviews'].str.strip() != ''][['ResponseName', 'Reviews']].head(3)
for _, row in with_reviews.iterrows():
    print(f"\nGame: {row['ResponseName']}")

---Game Review Columns---

Game: Red Orchestra: Ostfront 41-45

Game: Arx Fatalis

Game: Earth 2160